### ISSUE TITLE
Unknown error on start

### ISSUE THREAD

**Issue by rbarbadillo** [tinybirdco/vscode-tinybird-support#27]
When opening the extension tab on VSCode, I get the error "An unknown error occurred. Please consult the log for more details."

Syntax highlighting and the file symbol still working:

![Screenshot from 2023-10-02 10-45-30](https://github.com/tinybirdco/vscode-tinybird-support/assets/38496681/a57a6ce5-8ec1-4ca2-a057-17e5dcc8878f)

**Comment by rbarbadillo** [comment]
It seems it's an authentication issue. I am using a user token on the `.tinyb` file. Logs:

```
notificationsAlerts.ts:40 Error: 
    at Object.fetchPipes (/home/rbarbadillo/.vscode/extensions/tinybirdco.vscode-tinybird-support-1.0.2/src/context.ts:70:15)
    at process.getPipes (node:internal/process/task_queues:95:5)
    at d.getChildren (/home/rbarbadillo/.vscode/extensions/tinybirdco.vscode-tinybird-support-1.0.2/src/views/pipes.ts:55:34)
    at c.Y (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:66905)
    at c.getChildren (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:63275)
c @ notificationsAlerts.ts:40
notificationsAlerts.ts:40 Error: 
    at d.getChildren (/home/rbarbadillo/.vscode/extensions/tinybirdco.vscode-tinybird-support-1.0.2/src/views/tokens.ts:45:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at c.Y (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:66905)
    at c.getChildren (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:63275)
c @ notificationsAlerts.ts:40
notificationsAlerts.ts:40 Error: 
    at Object.fetchDataSources (/home/rbarbadillo/.vscode/extensions/tinybirdco.vscode-tinybird-support-1.0.2/src/context.ts:81:15)
    at process.getDataSources (node:internal/process/task_queues:95:5)
    at d.getChildren (/home/rbarbadillo/.vscode/extensions/tinybirdco.vscode-tinybird-support-1.0.2/src/views/datasources.ts:57:22)
    at c.Y (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:66905)
    at c.getChildren (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:125:63275)
c @ notificationsAlerts.ts:40
```

**Comment by rbarbadillo** [comment]
OK so what was going on was:
- The API was returning a 403 => Added a better log for that error.
- The first-loaded token from the `.tinyb` file was incorrect. I changed it on the file but it was not refreshing. I have added a line to clear the Token from the context info on start, to make sure it is loaded on start.
